services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["sleep", "infinity"]
    ports:
      - "3000:3000"
    volumes:
      - .:/rails_blog
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/rails_blog_development
      - REDIS_URL=redis://redis:6379/1
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
